

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mapa-osc-front
    container_name: mapa-osc-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
    ports:
      - "8000:8000"
    networks:
      - mapa-osc
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5434
    dns:
      - 8.8.8.8
      - 1.1.1.1
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  mapa-osc:
    driver: bridge